### ISSUE TITLE
arweave.js is not defined in smartweave interact-contract (likely was not initialized properly)

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/node#11]
![image](https://user-images.githubusercontent.com/37120777/120116827-5f033900-c160-11eb-9012-846326ca2347.png)

**Comment by AndreVallestero** [comment]
This was a result of an outdated SDK version. It was fixed with https://github.com/open-koi/node/commit/1978387054beac08fd473b9c2e997a5bd6d0c4db
