### ISSUE TITLE
Direct witness mode checks expired votes 

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/node#27]
We should probably just skip output on expired votes during startup

![image](https://user-images.githubusercontent.com/37120777/121266441-e3f0ff80-c890-11eb-8fa2-5ec77fb52ee0.png)

**Comment by AndreVallestero** [comment]
@Maki44 @Sebhatu Would it be possible to skip on expired votes? Would this cause any issues? This should be as simple as checking if block height is within the vote.start and vote.end, correct?

**Comment by Maki44** [comment]
we can just not console the expired vote, I think I can fix that.

**Comment by AndreVallestero** [comment]
> we can just not console the expired vote, I think I can fix that.

That's not the issue, the issue is that it's slow to iterate over all the expired votes. If the state has gone through 10000 votes, it would take an hour before a new witness node could vote. This is not scalable.
