### ISSUE TITLE
Messy logs in debug

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/node#6]
![image](https://user-images.githubusercontent.com/37120777/120109851-90204100-c141-11eb-9b54-29f9ba444c8c.png)

**Comment by AndreVallestero** [comment]
This is fixed in refactor https://github.com/open-koi/node_cli/pull/5

**Comment by AndreVallestero** [comment]
Leaving open until merged into main

**Comment by AndreVallestero** [comment]
Resolved by https://github.com/open-koi/node/pull/5
