### ISSUE TITLE
Unhandled kyve error causes node failure

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/node#7]
![image](https://user-images.githubusercontent.com/37120777/120112202-43416800-c14b-11eb-8742-91f621f49ed5.png)

**Comment by AndreVallestero** [comment]
Should be resolved by https://github.com/open-koi/tools/pull/45 and https://github.com/open-koi/tools/commit/cbc71db8c7b3c3bb4ef8693aaa8979249dfe363a
