### ISSUE TITLE
'key file location' should persist between node runtimes

### ISSUE THREAD

**Issue by alexander-morris** [open-koi/node#9]

**Comment by AndreVallestero** [comment]
Is it adequate to check if KEY_FILE_LOCATION is in `.env` before asking? Or do you want manually entered key file locations to be saved? The latter could be annoying if you would like to switch to a different keyfile but it automatically uses the old one.

**Comment by alexander-morris** [comment]
I think it should probably be something that runs like a daemon with persistent memory

**Comment by AndreVallestero** [comment]
This is partially solved with https://github.com/open-koi/node/pull/17 as you can set `AR_WALLET=/path/to/wallet` in `.env` to keep it persistent.
